insert into ACCOUNTSYSTEM.ACCOUNTTYPE (TYPE_ID, DATE_CREATED, MNEMONIC, TYPE_NAME) values (5001, '2020-01-01', 'MILES', 'Miles');
insert into ACCOUNTSYSTEM.ACCOUNTTYPE (TYPE_ID, DATE_CREATED, MNEMONIC, TYPE_NAME) values (5002, '2020-01-01', 'MILES', 'Miles');
